apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
  labels:
    app: weatherapp
   namespace: weather
spec:
  selector:
    matchLabels:
      app: weatherapp
  replicas: 3
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: dipugodocker/weatherapp:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: weatherendpoint
